version: '2'
services:
  app_server:
    env_file:
      - fileName
    image: hydrian/osticket-docker:latest
    restart: always
    networks:
      - osticket_net
    ports:
      - 8070:127.0.0.1:8070
    volumes:
      - osticket_userfiles:/var/www/user_files
      - osticket_config:/var/www/html/include/ost-config.php
  maria_db:
    image: mariadb:11.2
    networks:
      - osticket_net
    restart: always
    volumes:
      - osticket_db:/var/lib/mysql
  memcache:
    networks:
      - osticket_net
    image: memcache:1.6
    restart: always
volumes:
  osticket_db:
  osticket_userfiles:
  osticket_config:
networks:
  osticket_net: