version: '2'
services:
  app_server:
    env_file:
      - fileName
    image: hydrian/osticket:latest
    restart: always
    networks:
      - osticket_net
    ports:
      - 127.0.0.1:8070:8070
    volumes:
      - osticket_userfiles:/var/www/user_files
      - osticket_config:/var/www/html/include/ost-config.php
      - osticket_logs:/logs
  maria_db:
    image: mariadb:lts-noble
    networks:
      - osticket_net
    restart: always
    volumes:
      - osticket_db:/var/lib/mysql
  memcache:
    networks:
      - osticket_net
    image: memcached:1.6
    restart: always
volumes:
  osticket_db:
  osticket_userfiles:
  osticket_config:
  osticket_logs:
  osticket_backups:
networks:
  osticket_net:
